paths:
  cal_file_path: "/Users/sanuma/LF_lens2_reproduce2/SpindleCal.txt"
  cutparams_filepath: "/Users/sanuma/LF_lens2_reproduce2/Silicon_LF_Cut_params.txt"

spindles:
  SpindleB:
    type: "Thick"
    blade_diameter: 81.4
  SpindleC:
    type: "Med"
    blade_diameter: 81.4
  SpindleD:
    type: "Thin"
    blade_diameter: 82.8

orientations:
  0deg:
    flange_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/0deg/Flange_Met_0deg.dat'
    plane_metrology_file_path: 'path to planemet 0 deg.dat'
    base_dir: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT2/LF/Lens2/Convex/Odeg'
  90deg:
    flange_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2    /Convex/0deg/Flange_Met_90deg.dat'
    plane_metrology_file_path: 'path to planemet 90 deg.dat'
    base_dir: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/9Odeg'
