paths:
  cal_file_path: "/Users/sanuma/LF_lens2_reproduce2/SpindleCal.txt"
  cutparams_filepath: "/Users/sanuma/LF_lens2_reproduce2/Silicon_LF_Cut_params.txt"

spindles:
  SpindleB:
    type: "Thick"
    blade_diameter: 81.4
  SpindleC:
    type: "Med"
    blade_diameter: 81.4
  SpindleD:
    type: "Thin"
    blade_diameter: 82.8

orientations:
  0deg:
    lens_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/0deg/Lens_Met_0deg.dat'
    flange_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/0deg/Flange_Met_0deg.dat'
    plane_metrology_file_path: 'path to planemet 0 deg.dat'
    base_dir: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT2/LF/Lens2/Convex/Odeg'
  90deg:
    lens_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/0deg/Lens_Met_90deg.dat'
    flange_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2    /Convex/0deg/Flange_Met_90deg.dat'
    plane_metrology_file_path: 'path to planemet 90 deg.dat'
    base_dir: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/9Odeg'
  180deg:
    lens_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/0deg/Lens_Met_180deg.dat'
    flange_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2    /Convex/0deg/Flange_Met_180deg.dat'
    base_dir: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/18Odeg'
  270deg:
    lens_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/0deg/Lens_Met_270deg.dat'
    flange_metrology_file_path: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2    /Convex/0deg/Flange_Met_270deg.dat'
    base_dir: '/Users/sanuma/LF_lens2_reproduce2/SO_SAT/LF/Lens2/Convex/27Odeg'



    ## other params?
    ## maybe worth adding flood port information too which won't be used for metalens but would be used for automation1? that way, no new config file just for automation1 python code. all just accessible here?
    #
    #TODO: now code can build {base_dir}/{spindle}/CutCamming{type}-Noshift
