SpindleB:
  x_center_shift: '0'
  x_postcal_shift: '+0.010'
  y_postcal_shift: '0'
  zcorr:
    0deg: '-0.02834'
    90deg: '0'
    180deg: '0'
    270deg: '0'

SpindleC:
  x_center_shift: '0'
  x_postcal_shift: '0'
  y_postcal_shift: '0'
  zcorr:
    0deg: '+0.28504'
    90deg: '0'
    180deg: '0'
    270deg: '0'

SpindleD:
  x_center_shift: '0'
  x_postcal_shift: '+0.010'
  y_postcal_shift: '0'
  zcorr:
    0deg: '+0.06834'
    90deg: '0'
    180deg: '0'
    270deg: '0'
  
