paths:
  cal_file_path: "path to spindle calibration file"
  cutparams_filepath: "path to silicon LF cut params file for example"

spindles:
  SpindleB:
    type: "Thick"
    blade_diameter: 78.2
  SpindleC:
    type: "Med"
    blade_diameter: 78.2
  SpindleD:
    type: "Thin"
    blade_diameter: 78.2

orientations:
  0deg:
    metrology_file_path: 'path to 0deg metrology'
    base_dir: '/Users/SAT_LF/Lens3/Surface1/Odeg'
  90deg:
    metrology_file_path: 'path to 90deg metrology'
    base_dir: '/Users/SAT_LF/Lens3/Surface1/9Odeg'
  180deg:
    metrology_file_path: 'path to 180deg metrology'
    base_dir: '/Users/SAT_LF/Lens3/Surface1/18Odeg'
  270deg:
    metrology_file_path: 'path to 270deg metrology'
    base_dir: '/Users/SAT_LF/Lens3/Surface1/27Odeg'



    ## other params?
    ## maybe worth adding flood port information too which won't be used for metalens but would be used for automation1? that way, no new config file just for automation1 python code. all just accessible here?
    #
    #TODO: now code can build {base_dir}/{spindle}/CutCamming{type}-Noshift
